# Generated by Django 4.2.24 on 2025-09-27 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(default='Series 1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('number', models.PositiveIntegerField()),
                ('rarity', models.CharField(choices=[('o', 'Обычная'), ('ск', 'Средняя карта'), ('ук', 'Ультра карта')], max_length=2)),
                ('base_price_rub', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.series')),
            ],
            options={
                'ordering': ['series__number', 'number'],
                'unique_together': {('series', 'number')},
            },
        ),
        migrations.CreateModel(
            name='CardTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.tag')),
            ],
            options={
                'unique_together': {('card', 'tag')},
            },
        ),
    ]
