# Generated by Django 4.2.24 on 2025-09-27 05:37

import apps.inventory.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_card', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(choices=[('M', 'Mint'), ('NM', 'Near Mint'), ('SP', 'Slightly Played'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('DM', 'Damaged'), ('NO', 'Нет в коллекции')], default='NO', max_length=2)),
                ('user_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('note', models.TextField(blank=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='cards.card')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('card', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.inventory.models.card_image_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.inventoryitem')),
            ],
        ),
    ]
