# Generated by Django 4.2.24 on 2025-10-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ник в Telegram'),
        ),
    ]
