# Generated by Django 4.2.24 on 2025-10-17 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(db_index=True, help_text='Уникальный код для проверки карты', max_length=100, unique=True, verbose_name='Код верификации')),
                ('is_active', models.BooleanField(default=True, help_text='Можно ли проверить эту карту', verbose_name='Активна')),
                ('verification_count', models.PositiveIntegerField(default=0, help_text='Сколько раз карту проверяли', verbose_name='Количество проверок')),
                ('owner_info', models.TextField(blank=True, help_text='Опциональная информация о текущем владельце', verbose_name='Информация о владельце')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные заметки о карте', verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='cards.card', verbose_name='Карта')),
            ],
            options={
                'verbose_name': 'Верифицированная карта',
                'verbose_name_plural': 'Верифицированные карты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(help_text='ID пользователя, который проверил карту', verbose_name='ID пользователя Telegram')),
                ('telegram_username', models.CharField(blank=True, max_length=200, verbose_name='Username Telegram')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата проверки')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('verified_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='telegram_bot.verifiedcard', verbose_name='Верифицированная карта')),
            ],
            options={
                'verbose_name': 'Лог верификации',
                'verbose_name_plural': 'Логи верификаций',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='verifiedcard',
            index=models.Index(fields=['verification_code'], name='telegram_bo_verific_5b04af_idx'),
        ),
        migrations.AddIndex(
            model_name='verifiedcard',
            index=models.Index(fields=['is_active', 'created_at'], name='telegram_bo_is_acti_b523a0_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['verified_card', 'checked_at'], name='telegram_bo_verifie_472111_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['telegram_user_id', 'checked_at'], name='telegram_bo_telegra_5abcd9_idx'),
        ),
    ]
