# Generated by Django 4.2.24 on 2025-10-17 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedcard',
            name='card_name',
            field=models.CharField(blank=True, default='', help_text='Название карты', max_length=255, verbose_name='Название карты'),
        ),
        migrations.AddField(
            model_name='verifiedcard',
            name='description',
            field=models.TextField(blank=True, help_text='Описание карты от администратора', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='verifiedcard',
            name='photo_original',
            field=models.ImageField(blank=True, help_text='Фото карты до упаковки', null=True, upload_to='cards/original/', verbose_name='Фото карты (оригинал)'),
        ),
        migrations.AddField(
            model_name='verifiedcard',
            name='photo_packaged',
            field=models.ImageField(blank=True, help_text='Фото карты после упаковки с QR-кодом', null=True, upload_to='cards/packaged/', verbose_name='Фото карты в упаковке'),
        ),
        migrations.AlterField(
            model_name='verifiedcard',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='cards.card', verbose_name='Карта из каталога'),
        ),
    ]
